### ISSUE TITLE
Multiple problems with password reset flow

### ISSUE THREAD

**Issue by cnelson** [18F/cg-uaa-extras#88]
When working with a customer to diagnosis an issue with password reset several issues were discovered:

## Users who don't have an account receive an email.

If a user without an account attempts a password reset, they receive an email anyway which leads them to believe they have an account.  This app should probably silently ignore any requests for password reset for accounts that don't exist.

## Using the password reset link more than once results in an internal server error.

If an error occurs during the password reset flow and the user attempts to reset a second time by pressing the back button or clicking the link in the email a second time, an Internal Server Error is displayed providing no helpful information.  The stack trace for when this occurs is included below

    [2017-03-14 14:02:53,547] ERROR in app: Exception on /reset-password [POST]
    Traceback (most recent call last):
      File "/app/.heroku/python/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
        response = self.full_dispatch_request()
      File "/app/.heroku/python/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/app/.heroku/python/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/app/.heroku/python/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
        raise value
      File "/app/.heroku/python/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
        rv = self.dispatch_request()
      File "/app/.heroku/python/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/vcap/app/uaaextras/webapp.py", line 739, in reset_password
        if userToken.decode('utf-8') == token:
    AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by brittag** [comment]
I'm not sure if we fixed the second issue, so I'll reopen this for now.

**Comment by brittag** [comment]
We got confirmation via support emails that the second problem is not fixed. :p
